// Regenerable PSGC importer: fetch the API → write idempotent upserts as a committed
// migration. Run: `node scripts/import-psgc.mjs`. No runtime dependency on the API.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const API = "https://psgc.gitlab.io/api";
const OUT = new URL("../supabase/migrations/20260720140100_psgc_data.sql", import.meta.url);

export const mapRegion = (r) => ({ code: r.code, name: r.name, region_name: r.regionName ?? null, island_group_code: r.islandGroupCode ?? null });
export const mapProvince = (p) => ({ code: p.code, name: p.name, region_code: p.regionCode, island_group_code: p.islandGroupCode ?? null });
export const mapCity = (c) => ({ code: c.code, name: c.name, is_city: !!c.isCity, province_code: c.provinceCode || null, region_code: c.regionCode, island_group_code: c.islandGroupCode ?? null });

const lit = (v) => v === null || v === undefined ? "null" : typeof v === "boolean" ? String(v) : `'${String(v).replace(/'/g, "''")}'`;

function upserts(table, cols, rows) {
  if (!rows.length) return "";
  const values = rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(",")})`).join(",\n");
  const set = cols.filter((c) => c !== "code").map((c) => `${c}=excluded.${c}`).join(", ");
  return `insert into ${table} (${cols.join(",")}) values\n${values}\non conflict (code) do update set ${set};\n`;
}

async function main() {
  const [regions, provinces, cities] = await Promise.all([
    fetch(`${API}/regions.json`).then((r) => r.json()),
    fetch(`${API}/provinces.json`).then((r) => r.json()),
    fetch(`${API}/cities-municipalities.json`).then((r) => r.json()),
  ]);
  const sql = [
    "-- GENERATED by scripts/import-psgc.mjs — do not edit by hand. Re-run to refresh.",
    upserts("psgc_regions", ["code", "name", "region_name", "island_group_code"], regions.map(mapRegion)),
    upserts("psgc_provinces", ["code", "name", "region_code", "island_group_code"], provinces.map(mapProvince)),
    upserts("psgc_cities", ["code", "name", "is_city", "province_code", "region_code", "island_group_code"], cities.map(mapCity)),
  ].join("\n");
  writeFileSync(OUT, sql);
  console.log(`Wrote ${regions.length} regions, ${provinces.length} provinces, ${cities.length} cities → ${OUT.pathname}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
